services:
  - type: web
    name: document-chatbot
    env: docker
    plan: starter 
    healthCheckPath: /health
    envVars:
      - key: HUGGINGFACEHUB_API_TOKEN
        sync: false
      - key: SECRET_KEY
        sync: false
