services:
  - type: web
    name: document-chatbot
    # Tell Render to use Docker to solve the build issue
    env: docker
    plan: starter # Or your current plan
    # Health check path
    healthCheckPath: /health
    envVars:
      - key: HUGGINGFACEHUB_API_TOKEN
        sync: false
      - key: SECRET_KEY
        sync: false
