services:
  - type: web
    name: document-chatbot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app"
    envVars:
      - key: HUGGINGFACEHUB_API_TOKEN
        sync: false
      - key: SECRET_KEY
        sync: false